const products = [
    {
        id: 1,
        Name: 'Bánh bèo Huế',
        Description: 'Bánh bèo Huế-Đặc sản cố đô văn hiến',
        packageQuantity: 20,
        soldQuantity: 100,
        OriginalPrice: 20000,
        Discount: 10,
        salePrice: 18000,
        image: 'https://res.cloudinary.com/dpsqln4rh/image/upload/v1726502831/focodo_ecommerce/product/yjojahq8kmzk5nb7c6ta.jpg',
        rating: 4.2,
    },
    {
        id: 2,
        Name: 'Bánh bèo Huế',
        Description: 'Bánh bèo Huế-Đặc sản cố đô văn hiến',
        packageQuantity: 20,
        soldQuantity: 100,
        OriginalPrice: 20000,
        Discount: 20,
        salePrice: 16000,
        image: 'https://res.cloudinary.com/dpsqln4rh/image/upload/v1726503863/focodo_ecommerce/product/lon4iw5tymjl2ipylyux.jpg',
        rating: 3.4,
    },
    {
        id: 3,
        Name: 'Bánh bèo Huế',
        Description: 'Bánh bèo Huế-Đặc sản cố đô văn hiến',
        packageQuantity: 20,
        soldQuantity: 100,
        OriginalPrice: 20000,
        Discount: 20,
        salePrice: 16000,
        image: 'https://res.cloudinary.com/dpsqln4rh/image/upload/v1726753286/focodo_ecommerce/product/zydq7mua8cnwodexwywg.webp',
        rating: 2.5,
    },
    {
        id: 4,
        Name: 'Bánh bèo Huế',
        Description: 'Bánh bèo Huế-Đặc sản cố đô văn hiến',
        packageQuantity: 20,
        soldQuantity: 100,
        OriginalPrice: 20000,
        Discount: 25,
        salePrice: 15000,
        image: 'https://res.cloudinary.com/dpsqln4rh/image/upload/v1726988921/focodo_ecommerce/product/sbeahuqzw2rlejg8i2cr.jpg',
        rating: 4,
    },
    {
        id: 5,
        Name: 'Bánh bèo Huế',
        Description: 'Bánh bèo Huế-Đặc sản cố đô văn hiến',
        packageQuantity: 20,
        soldQuantity: 100,
        OriginalPrice: 20000,
        Discount: 20,
        salePrice: 16000,
        image: 'https://cdn.tgdd.vn/2021/07/CookProduct/bthum-1200x676-2.jpg',
        rating: 4,
    },
    {
        id: 6,
        Name: 'Bánh bèo Huế',
        Description: 'Bánh bèo Huế-Đặc sản cố đô văn hiến',
        packageQuantity: 20,
        soldQuantity: 100,
        OriginalPrice: 20000,
        Discount: 20,
        salePrice: 16000,
        image: 'https://cdn.tgdd.vn/2021/07/CookProduct/bthum-1200x676-2.jpg',
        rating: 4,
    },
    {
        id: 7,
        Name: 'Bánh bèo Huế',
        Description: 'Bánh bèo Huế-Đặc sản cố đô văn hiến',
        packageQuantity: 20,
        soldQuantity: 100,
        OriginalPrice: 25000,
        Discount: 20,
        salePrice: 20000,
        image: 'https://cdn.tgdd.vn/2021/07/CookProduct/bthum-1200x676-2.jpg',
        rating: 4,
    },
    {
        id: 8,
        Name: 'Bánh bèo Huế',
        Description: 'bánh bèo Huế-Đặc sản cố đô văn hiến',
        packageQuantity: 20,
        soldQuantity: 100,
        OriginalPrice: 20000,
        Discount: 20,
        salePrice: 16000,
        image: 'https://cdn.tgdd.vn/2021/07/CookProduct/bthum-1200x676-2.jpg',
        rating: 4,
    },
    {
        id: 9,
        Name: 'Bánh bèo Huế',
        Description: 'bánh bèo Huế-Đặc sản cố đô văn hiến',
        packageQuantity: 20,
        soldQuantity: 100,
        OriginalPrice: 20000,
        Discount: 20,
        salePrice: 16000,
        image: 'https://cdn.tgdd.vn/2021/07/CookProduct/bthum-1200x676-2.jpg',
        rating: 4,
    },
    {
        id: 10,
        Name: 'Bánh bèo Huế',
        Description: 'Bánh bèo Huế-Đặc sản cố đô văn hiến',
        packageQuantity: 20,
        soldQuantity: 100,
        OriginalPrice: 20000,
        Discount: 20,
        salePrice: 16000,
        image: 'https://cdn.tgdd.vn/2021/07/CookProduct/bthum-1200x676-2.jpg',
        rating: 4,
    },
];

export default products;
